data1<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors = FALSE)
datatouse<-subset(data1,Date=='1/2/2007'|Date=='2/2/2007')
datatouse$Global_active_power<-as.numeric(datatouse$Global_active_power)
png('plot2')
plot(datatouse$Global_active_power, type="l", ylab="Global Active Power",xaxt='n')
axis(1, at=1500, labels="Fri")
axis(1, at=0, labels="Thur")
axis(1, at=2880, labels="Sat")
dev.off()
