data1<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors = FALSE)
datatouse<-subset(data1,Date=='1/2/2007'|Date=='2/2/2007')
datatouse$Global_active_power<-as.numeric(datatouse$Global_active_power)

png('plot4')
par(mfrow=c(2,2))
plot(datatouse$Global_active_power,type="l",ylab= "Global Active Power",xaxt='n')
axis(1, at=1500, labels="Fri")
axis(1, at=0, labels="Thur")
axis(1, at=2880, labels="Sat")

plot(datatouse$Voltage,type="l",ylab="Voltage",xlab="datetime",xaxt='n')
axis(1, at=1500, labels="Fri")
axis(1, at=0, labels="Thur")
axis(1, at=2880, labels="Sat")

plot (datatouse$Sub_metering_1,type="n",ylab="Energy Metering",xaxt='n')
lines(datatouse$Sub_metering_1,type="l",col="black")
lines(datatouse$Sub_metering_2,type="l",col="red")
lines(datatouse$Sub_metering_3,type="l",col="blue")
legend("topright",pch=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.7)
axis(1, at=1500, labels="Fri")
axis(1, at=0, labels="Thur")
axis(1, at=2880, labels="Sat")

plot(datatouse$Global_reactive_power,type="l",ylab="Global_Reactive_Power",xaxt='n',xlab='datetime')
axis(1, at=1500, labels="Fri")
axis(1, at=0, labels="Thur")
axis(1, at=2880, labels="Sat")
dev.off()
